# Travis CI Configuration File

# Tell Travis CI we're using PHP
language: php

php:
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'

install: composer install

script:
  - vendor/bin/phpcs .
  - vendor/bin/phpunit ./tests/*
